# build and save build to dist

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: build
        run: npm run build
      - name: Check changes to build
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Commit files
        if: steps.changes.outputs.changed == 1
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./dist
          git commit -m "[CI] Updating dist files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

